require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PupilHasYearsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PupilHasYear. As you add validations to PupilHasYear, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PupilHasYearsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pupil_has_years as @pupil_has_years" do
      pupil_has_year = PupilHasYear.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:pupil_has_years)).to eq([pupil_has_year])
    end
  end

  describe "GET show" do
    it "assigns the requested pupil_has_year as @pupil_has_year" do
      pupil_has_year = PupilHasYear.create! valid_attributes
      get :show, {:id => pupil_has_year.to_param}, valid_session
      expect(assigns(:pupil_has_year)).to eq(pupil_has_year)
    end
  end

  describe "GET new" do
    it "assigns a new pupil_has_year as @pupil_has_year" do
      get :new, {}, valid_session
      expect(assigns(:pupil_has_year)).to be_a_new(PupilHasYear)
    end
  end

  describe "GET edit" do
    it "assigns the requested pupil_has_year as @pupil_has_year" do
      pupil_has_year = PupilHasYear.create! valid_attributes
      get :edit, {:id => pupil_has_year.to_param}, valid_session
      expect(assigns(:pupil_has_year)).to eq(pupil_has_year)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PupilHasYear" do
        expect {
          post :create, {:pupil_has_year => valid_attributes}, valid_session
        }.to change(PupilHasYear, :count).by(1)
      end

      it "assigns a newly created pupil_has_year as @pupil_has_year" do
        post :create, {:pupil_has_year => valid_attributes}, valid_session
        expect(assigns(:pupil_has_year)).to be_a(PupilHasYear)
        expect(assigns(:pupil_has_year)).to be_persisted
      end

      it "redirects to the created pupil_has_year" do
        post :create, {:pupil_has_year => valid_attributes}, valid_session
        expect(response).to redirect_to(PupilHasYear.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pupil_has_year as @pupil_has_year" do
        post :create, {:pupil_has_year => invalid_attributes}, valid_session
        expect(assigns(:pupil_has_year)).to be_a_new(PupilHasYear)
      end

      it "re-renders the 'new' template" do
        post :create, {:pupil_has_year => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pupil_has_year" do
        pupil_has_year = PupilHasYear.create! valid_attributes
        put :update, {:id => pupil_has_year.to_param, :pupil_has_year => new_attributes}, valid_session
        pupil_has_year.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested pupil_has_year as @pupil_has_year" do
        pupil_has_year = PupilHasYear.create! valid_attributes
        put :update, {:id => pupil_has_year.to_param, :pupil_has_year => valid_attributes}, valid_session
        expect(assigns(:pupil_has_year)).to eq(pupil_has_year)
      end

      it "redirects to the pupil_has_year" do
        pupil_has_year = PupilHasYear.create! valid_attributes
        put :update, {:id => pupil_has_year.to_param, :pupil_has_year => valid_attributes}, valid_session
        expect(response).to redirect_to(pupil_has_year)
      end
    end

    describe "with invalid params" do
      it "assigns the pupil_has_year as @pupil_has_year" do
        pupil_has_year = PupilHasYear.create! valid_attributes
        put :update, {:id => pupil_has_year.to_param, :pupil_has_year => invalid_attributes}, valid_session
        expect(assigns(:pupil_has_year)).to eq(pupil_has_year)
      end

      it "re-renders the 'edit' template" do
        pupil_has_year = PupilHasYear.create! valid_attributes
        put :update, {:id => pupil_has_year.to_param, :pupil_has_year => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pupil_has_year" do
      pupil_has_year = PupilHasYear.create! valid_attributes
      expect {
        delete :destroy, {:id => pupil_has_year.to_param}, valid_session
      }.to change(PupilHasYear, :count).by(-1)
    end

    it "redirects to the pupil_has_years list" do
      pupil_has_year = PupilHasYear.create! valid_attributes
      delete :destroy, {:id => pupil_has_year.to_param}, valid_session
      expect(response).to redirect_to(pupil_has_years_url)
    end
  end

end
